# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build LectureFeed

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Clone Subproject
      run: rm -rf "src/main/resources/LectureFeed-Web" && cd "src/main/resources/LectureFeed-Web" && git clone https://github.com/MaximilianLincks/LectureFeed-Web.git

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install
      run: cd "src/main/resources/LectureFeed-Web" && npm install
                
    - name: Run tests
      run: cd "src/main/resources/LectureFeed-Web" && npm run test-server
                
    - name: Build
      run: cd "src/main/resources/LectureFeed-Web" && npm run build
      
    - name: Delete Subproject
      run: sudo chown -R $USER:$USER "src/main/resources/LectureFeed-Web" && rm -rf "src/main/resources/LectureFeed-Web"
    
    #- uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Packing
      run: mkdir staging && cp target/*.jar staging
    - uses: actions/upload-artifact@v1
      with:
        name: Package
        path: staging
