name: 'Notify LFD-Desktop'

on:
  push:
    branches:
      - main    

jobs:
  notify:
    name: 'Notify LFD-Desktop'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
    
    steps:
    - name: Github REST API Call
      env:
        CI_TOKEN: ${{ secrets.CI_TOKEN }}
      run: |
        curl -X POST -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ env.CI_TOKEN }}" https://api.github.com/repos/MaximilianLincks/LectureFeed-Desktop/actions/workflows/build.yml/dispatches -d '{"ref":"main"}'        
